const CartActionTypes = {
  ADD_ITEM: 'ADD_ITEM',
  REDUCE_ITEM: 'REDUCE_ITEM',
  INCREASE_ITEM: 'INCREASE_ITEM',
  CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
  CLEAR_ALL_ITEMS: 'CLEAR_ALL_ITEMS',
  CLEAR_NO_STOCK_ITEMS: 'CLEAR_NO_STOCK_ITEMS',
  SET_ITEM_SELLING_PRICE: 'SET_ITEM_SELLING_PRICE',
};

export default CartActionTypes;
