const ShopDataActionTypes = {
  SET_CLIENT_INFO: 'SET_CLIENT_INFO',
  CLEAR_CLIENT_INFO: 'CLEAR_CLIENT_INFO',
  CONFIRM_ORDER: 'CONFIRM_ORDER',
  UNCONFIRM_ORDER: 'UNCONFIRM_ORDER',
  UPDATE_DELIVERY_TYPE: 'UPDATE_DELIVERY_TYPE'
};

export default ShopDataActionTypes;
